### ISSUE TITLE
Yosemite aliases not working

### ISSUE THREAD

**Issue by tizzo** [airtonix/avahi-aliases#7] opened 2015-01-05 19:12 UTC
I suspect this is an issue more with Yosemite but I'll ask here in case anyone has input.  On Mountain  Lion my Ubuntu 12.04 Vagrant VM resolves aliases but on my new Mavericks machine the aliases do not resolve.  In both cases local.local (the main Avahi A record) resolve perfectly, on Mountain Lion the aliases work as well, on Yosemite they do not.

Any ideas what I might be doing wrong or might need to change?

[Edit January 7, 2015: I had typed Mavericks but meant Yosemite]

**Comment by heavi5ide** [comment] 2015-01-07 14:23
We have this issue at my office as well, but with Yosemite, not Mavericks. Everyone was fine in Mavericks, but after upgrading to Yosemite, subdomains of `myvm.local` (a vagrant/virtualbox VM) published using avahi-aliases do not resolve in OS X anymore. It appears that Yosemite no longer understands the CNAMEs published by avahi. When I try

`dns-sd -q api.myvm.local`

I get

```
Timestamp     A/R Flags if Name                          Type  Class   Rdata
23:48:15.276  Add     2  4 api.myvm.local.               CNAME  IN     myvm.local.
```

but this will not resolve in a browser (or with `ping` etc). `myvm.local` resolves just fine, but `api.myvm.local` does not.

**Comment by tizzo** [comment] 2015-01-07 15:08
:flushed: DURP! I'd been banging my head on this for way too long to write a coherent issue apparently.  Yes, it's Yosemite that I meant, my bad.

It makes sense that the mdns behavior might have changed given that in Yosemite `mDNSResponder` has been retired and replaced with `discoveryd`.  The former was open source, I can't find much on the latter.

Good call with the `dns-sd` command, I see the same.

I wonder if any work around is possible or if this is just a feature that's dropping with Yosemite.  I guess we would most likely would need Apple to change discoveryd.  Sounds like we're probably SOL?

**Comment by heavi5ide** [comment] 2015-01-07 20:31
Yeah, pretty sucky regression, and I doubt Apple is much concerned since there probably aren't many non-technical users affected. Hopefully I'm wrong?

The best I've been able to do so far is modify `/etc/hosts` on my mac with the VM's current IP address for all the aliases I need :frowning:

**Comment by tizzo** [comment] 2015-01-07 22:00
I just reported the bug to Apple's bug reporter, I'm sure you're right that they won't care at all.  Blargh.

**Comment by heavi5ide** [comment] 2015-01-07 22:33
Is there a link to your bug report so I can vote for it or anything? Sorry I'm lazy and don't want to go searching :\

**Comment by tizzo** [comment] 2015-01-07 23:46
No, I think all bug reports are private 😠. I'll keep this issue updated if I hear anything back.

**Comment by tizzo** [comment] 2015-01-27 17:08
Still no word from Apple.

**Comment by airtonix** [comment] 2015-03-04 05:26
Sorry guys I don't have access to MacOSx, but I'm more than happy to take direction on a strategy to deal with this, ie: pull-requests :)

**Comment by lenada** [comment] 2015-03-12 00:35
seems since 10.10.1 there is workaround
```
sudo defaults write \
        /System/Library/LaunchDaemons/com.apple.discoveryd.plist \
        ProgramArguments -array-add "--AlwaysAppendSearchDomains"
```
then reload discoveryd

```
sudo launchctl unload -w \
     /System/Library/LaunchDaemons/com.apple.discoveryd.plist
```

```
sudo launchctl load -w \
     /System/Library/LaunchDaemons/com.apple.discoveryd.plist
```

found here http://foo-blog.de/category/apple-mac/

**Comment by tizzo** [comment] 2015-03-18 21:06
I'm pretty sure that does not fix cnames, only subdomains.  The issue is
not that subdomains don't work - it's that cnames don't work.

**Comment by airtonix** [comment] 2015-03-19 23:35
On reflection, if avahi is work as per spec (an assumption), is this even a problem that I should be concerned with?

**Comment by airtonix** [comment] 2015-03-19 23:37
On reflection, if avahi is work as per spec (an assumption), is this even a problem that I should be concerned with?

closing this, since it's not a bug with `avahi` or `avahi-aliases`.

**Closed by airtonix** 2015-03-19 23:37 UTC
